import React, { useEffect, useState } from 'react';
import dayjs from 'dayjs';
import { createRoot } from 'react-dom/client';
import { Layout, Menu, Card, Statistic, Row, Col, Table, Button, Image, Drawer, Empty, Space, message, Select, DatePicker } from 'antd';
import 'antd/dist/reset.css';
import './style.css';

const { Sider, Header, Content } = Layout;
async function api(url, options) { const response = await fetch(url, { credentials: 'same-origin', ...options }); const data = await response.json(); if (!response.ok) throw Error(data.detail || '请求失败'); return data; }

function App() {
  const [tab, setTab] = useState('stats'); const [period, setPeriod] = useState('7d'); const [customDates, setCustomDates] = useState(null); const [stats, setStats] = useState(null); const [exceptions, setExceptions] = useState([]); const [detail, setDetail] = useState(null); const [loading, setLoading] = useState(false);
  const loadStats = (selected = period, dates = customDates) => { const params = new URLSearchParams({ period: selected }); if (selected === 'custom' && dates?.length === 2) { params.set('start_date', dates[0].format('YYYY-MM-DD')); params.set('end_date', dates[1].format('YYYY-MM-DD')); } return api(`/api/admin/statistics?${params}`).then(setStats).catch(e => message.error(e.message)); };
  const loadExceptions = () => { setLoading(true); api('/api/admin/exceptions?status=open').then(d => setExceptions(d.items)).catch(e => message.error(e.message)).finally(() => setLoading(false)); };
  useEffect(() => { loadStats(); loadExceptions(); }, []); const changePeriod = value => { setPeriod(value); if (value !== 'custom') loadStats(value); }; const changeCustomDates = dates => { setCustomDates(dates); if (dates?.length === 2) loadStats('custom', dates); };
  const resolve = async id => { await api(`/api/admin/exceptions/${id}/resolve`, { method: 'POST' }); message.success('已标记处理'); loadExceptions(); };
  const columns = [{ title: '查询时间', dataIndex: 'created_at', render: v => new Date(v).toLocaleString() }, { title: '客服', dataIndex: ['user', 'display_name'], render: v => v || '未知客服' }, { title: '客户图片', dataIndex: 'query_image_url', render: v => <Image className="exception-img" src={v} preview={{ src: v }} /> }, { title: '场景标签', dataIndex: 'query_scene', render: v => v ? Object.values(v).filter(Boolean).join(' / ') : '未识别' }, { title: '操作', render: (_, row) => <Space><Button size="small" onClick={() => api(`/api/admin/exceptions/${row.id}`).then(setDetail)}>查看</Button><Button size="small" type="primary" onClick={() => resolve(row.id)}>标记处理</Button></Space> }];
  return <Layout><Sider><div className="brand">买家秀后台</div><Menu theme="dark" selectedKeys={[tab]} onClick={e => setTab(e.key)} items={[{ key: 'stats', label: '客服数据' }, { key: 'exceptions', label: '异常待处理' }, { key: 'library', label: '买家秀库' }, { key: 'accounts', label: '客服子账户' }]} /></Sider><Layout><Header className="header">管理后台</Header><Content className="content">{tab === 'stats' && <><Card title="统计范围" className="filter-card"><Space><Select value={period} onChange={changePeriod} options={[{ value: 'today', label: '今日' }, { value: '7d', label: '近 7 天' }, { value: '30d', label: '近 30 天' }, { value: 'all', label: '全部' }, { value: 'custom', label: '自定义' }]} /><DatePicker.RangePicker value={customDates} disabled={period !== 'custom'} onChange={changeCustomDates} placeholder={['开始日期', '结束日期']} /></Space></Card><Row gutter={16}><Col span={8}><Card><Statistic title="匹配次数" value={stats?.total_matches || 0} /></Card></Col><Col span={8}><Card><Statistic title="成交次数" value={stats?.converted_matches || 0} /></Card></Col><Col span={8}><Card><Statistic title="转化率" value={stats?.conversion_rate || 0} suffix="%" /></Card></Col></Row><Card title="近 7 天趋势" className="trend"><Table rowKey="date" pagination={false} dataSource={stats?.trend || []} columns={[{ title: '日期', dataIndex: 'date' }, { title: '匹配次数', dataIndex: 'matches' }, { title: '成交次数', dataIndex: 'conversions' }]} /></Card></>}{tab === 'exceptions' && <Card title="无结果检索" extra={<Button onClick={loadExceptions}>刷新</Button>}><Table rowKey="id" loading={loading} dataSource={exceptions} columns={columns} locale={{ emptyText: <Empty description="暂无待处理异常" /> }} /></Card>}{tab === 'library' && <Card title="买家秀库"><Empty description="图库管理页面即将接入" /></Card>}{tab === 'accounts' && <Card title="客服子账户"><Empty description="沿用现有账号配置" /></Card>}<Drawer title="异常匹配详情" open={!!detail} onClose={() => setDetail(null)} width={560}>{detail && <><Image width="100%" src={detail.query_image_url} /><p>查询时间：{new Date(detail.created_at).toLocaleString()}</p><p>提示：{detail.payload?.message || '无'}</p><pre>{JSON.stringify(detail.payload?.query_scene || {}, null, 2)}</pre></>}</Drawer></Content></Layout></Layout>;
}
createRoot(document.getElementById('root')).render(<App />);
